version: "3"

services:
  chrome_scraper:
    container_name: chrome_standalone
    image: selenium/standalone-chrome:115.0
    env_file: .env
    restart: always
    shm_size: '2g'
    ports:
      - 4444:4444
      - 7900:7900