repos:
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length", "80"]
        files: '\.py$'
  - repo: local
    hooks:
      - id: npm-format
        name: "Format Scrapper"
        entry: npm run format
        language: system
        files: '^scrape/scraper_ts/.*\.(js|jsx)$'
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 2.3.2
  #   hooks:
  #     - id: sqlfluff-lint
  #       args: [--dialect, postgres]
  #       files: '\.sql$'
  #     - id: sqlfluff-fix
  #       args: [--dialect, postgres]
  #       files: '\.sql$'

  # - repo: https://github.com/doublify/pre-commit-rust
  #   rev: v1.0
  #   hooks:
  #   -   id: fmt
  #       files: '\.rs$'
  #   -   id: cargo-check
  #       files: '\.rs$'
    
fail_fast: false
