provider:
  supabase:
    plan:
      name: free
      pricing: null
      cycle: 20231204 - 20240104
    specs:
      storage: 1GB
      monthly_active_user: 50000
      realtime_peak_connection: 200
      egress_outgoing_traffic: 5GB
    urls:
      projects:
        xaola: https://supabase.com/dashboard/org/ojxfuiupnbmyrxkzbvuu
  bright_data:
    plan:
      plan_name: pay_as_you_go
      cycle: monthly
      pricing: null
    specs:
      proxy: 
        name: scraping_browser
    urls:
      user_setting: https://brightdata.com/cp/setting/users?id=hl_e97c9e12
  linode:
    plan: 
      plan_name: Nanode 1GB
      cycle: monthly
      pricing: $5/month, $0.0075/Hr
    specs:
      name: puppet_show-debian12-eu_central
      CPU_core: 1
      Storage: 25GB
      RAM: 1GB
      Volumes: 0
      Public_IP: 172.104.143.59
    url:
      instance_setting: https://cloud.linode.com/linodes/52844193/settings