version: "3"

services:
  postgres_xaola:
    container_name: postgres_xaola
    restart: unless-stopped
    build: 
      context: .
    env_file: .env
    volumes:
       - ./data:/var/lib/postgresql/data
       - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432